### PR TITLE
Adds support for probing URLs

### PR DESCRIPTION
**Pull request by fivepapertigers**
- Exposes a `from_url` method that allows probing URLs
- Validates url input and raises error if invalid url
- Raises an error if ffprobe response with an error message in the JSON

### CODE REVIEW

**Comment by beanieboi** [comment]
hey! thanks for that! thats amazing, I just fixed Travis CI. you can merge in master.

**Comment by fivepapertigers** [comment]
Ah! I just pushed a fix myself to see if it did the trick. I'll pop off that commit.

**Comment by beanieboi** [comment]
oh, whoops! sorry, my bad. I didn't refresh the PR page

**Comment by fivepapertigers** [comment]
No worries, neither did I.

**Comment by beanieboi** [comment]
one last thing, would you mind adding that features to the Changelog? (https://github.com/beanieboi/ffprober/blob/master/Changes.md). you can use "unreleased" as a version number

**Comment by fivepapertigers** [comment]
@beanieboi Just updated it. Let me know if you have any other requests. Thanks for the library, easy to use and easy develop in.

**Comment by beanieboi** [comment]
nothing from my side, just a big THANK YOU 👯‍♂️

**Pull request merged**
